export type TimeRange = "7d" | "30d" | "90d"

export interface ChartDataPoint {
  date: string
  hours: number
}

// Datos estáticos para 7 días
export const CHART_DATA_7_DAYS: ChartDataPoint[] = [
  { date: "Dic 16", hours: 2.5 },
  { date: "Dic 17", hours: 1.0 },
  { date: "Dic 18", hours: 3.0 },
  { date: "Dic 19", hours: 1.5 },
  { date: "Dic 20", hours: 2.0 },
  { date: "Dic 21", hours: 1.0 },
  { date: "Dic 22", hours: 2.5 },
]

// Datos estáticos para 30 días
export const CHART_DATA_30_DAYS: ChartDataPoint[] = [
  { date: "Nov 23", hours: 1.5 },
  { date: "Nov 24", hours: 2.0 },
  { date: "Nov 25", hours: 1.0 },
  { date: "Nov 26", hours: 0 },
  { date: "Nov 27", hours: 2.5 },
  { date: "Nov 28", hours: 1.5 },
  { date: "Nov 29", hours: 3.0 },
  { date: "Nov 30", hours: 2.0 },
  { date: "Dic 1", hours: 1.0 },
  { date: "Dic 2", hours: 0 },
  { date: "Dic 3", hours: 2.0 },
  { date: "Dic 4", hours: 1.5 },
  { date: "Dic 5", hours: 0 },
  { date: "Dic 6", hours: 2.5 },
  { date: "Dic 7", hours: 1.0 },
  { date: "Dic 8", hours: 3.0 },
  { date: "Dic 9", hours: 0 },
  { date: "Dic 10", hours: 1.5 },
  { date: "Dic 11", hours: 2.0 },
  { date: "Dic 12", hours: 1.0 },
  { date: "Dic 13", hours: 0 },
  { date: "Dic 14", hours: 2.5 },
  { date: "Dic 15", hours: 1.5 },
  { date: "Dic 16", hours: 2.0 },
  { date: "Dic 17", hours: 1.0 },
  { date: "Dic 18", hours: 3.0 },
  { date: "Dic 19", hours: 0 },
  { date: "Dic 20", hours: 2.0 },
  { date: "Dic 21", hours: 1.0 },
  { date: "Dic 22", hours: 2.5 },
]

// Datos estáticos para 90 días (aprox. 3 meses)
export const CHART_DATA_90_DAYS: ChartDataPoint[] = [
  { date: "Sep 24", hours: 1.5 },
  { date: "Sep 25", hours: 0 },
  { date: "Sep 26", hours: 2.0 },
  { date: "Sep 27", hours: 1.0 },
  { date: "Sep 28", hours: 0 },
  { date: "Sep 29", hours: 1.5 },
  { date: "Sep 30", hours: 2.5 },
  { date: "Oct 1", hours: 1.0 },
  { date: "Oct 2", hours: 0 },
  { date: "Oct 3", hours: 2.0 },
  { date: "Oct 4", hours: 1.5 },
  { date: "Oct 5", hours: 0 },
  { date: "Oct 6", hours: 1.0 },
  { date: "Oct 7", hours: 2.5 },
  { date: "Oct 8", hours: 1.5 },
  { date: "Oct 9", hours: 0 },
  { date: "Oct 10", hours: 2.0 },
  { date: "Oct 11", hours: 1.0 },
  { date: "Oct 12", hours: 0 },
  { date: "Oct 13", hours: 3.0 },
  { date: "Oct 14", hours: 1.5 },
  { date: "Oct 15", hours: 2.0 },
  { date: "Oct 16", hours: 0 },
  { date: "Oct 17", hours: 1.0 },
  { date: "Oct 18", hours: 2.5 },
  { date: "Oct 19", hours: 1.5 },
  { date: "Oct 20", hours: 0 },
  { date: "Oct 21", hours: 2.0 },
  { date: "Oct 22", hours: 1.0 },
  { date: "Oct 23", hours: 0 },
  { date: "Oct 24", hours: 2.5 },
  { date: "Oct 25", hours: 1.5 },
  { date: "Oct 26", hours: 3.0 },
  { date: "Oct 27", hours: 0 },
  { date: "Oct 28", hours: 2.0 },
  { date: "Oct 29", hours: 1.0 },
  { date: "Oct 30", hours: 0 },
  { date: "Oct 31", hours: 1.5 },
  { date: "Nov 1", hours: 2.5 },
  { date: "Nov 2", hours: 1.0 },
  { date: "Nov 3", hours: 0 },
  { date: "Nov 4", hours: 2.0 },
  { date: "Nov 5", hours: 1.5 },
  { date: "Nov 6", hours: 0 },
  { date: "Nov 7", hours: 3.0 },
  { date: "Nov 8", hours: 1.0 },
  { date: "Nov 9", hours: 0 },
  { date: "Nov 10", hours: 2.5 },
  { date: "Nov 11", hours: 1.5 },
  { date: "Nov 12", hours: 2.0 },
  { date: "Nov 13", hours: 0 },
  { date: "Nov 14", hours: 1.0 },
  { date: "Nov 15", hours: 2.5 },
  { date: "Nov 16", hours: 0 },
  { date: "Nov 17", hours: 1.5 },
  { date: "Nov 18", hours: 2.0 },
  { date: "Nov 19", hours: 1.0 },
  { date: "Nov 20", hours: 0 },
  { date: "Nov 21", hours: 2.5 },
  { date: "Nov 22", hours: 1.5 },
  { date: "Nov 23", hours: 1.5 },
  { date: "Nov 24", hours: 2.0 },
  { date: "Nov 25", hours: 1.0 },
  { date: "Nov 26", hours: 0 },
  { date: "Nov 27", hours: 2.5 },
  { date: "Nov 28", hours: 1.5 },
  { date: "Nov 29", hours: 3.0 },
  { date: "Nov 30", hours: 2.0 },
  { date: "Dic 1", hours: 1.0 },
  { date: "Dic 2", hours: 0 },
  { date: "Dic 3", hours: 2.0 },
  { date: "Dic 4", hours: 1.5 },
  { date: "Dic 5", hours: 0 },
  { date: "Dic 6", hours: 2.5 },
  { date: "Dic 7", hours: 1.0 },
  { date: "Dic 8", hours: 3.0 },
  { date: "Dic 9", hours: 0 },
  { date: "Dic 10", hours: 1.5 },
  { date: "Dic 11", hours: 2.0 },
  { date: "Dic 12", hours: 1.0 },
  { date: "Dic 13", hours: 0 },
  { date: "Dic 14", hours: 2.5 },
  { date: "Dic 15", hours: 1.5 },
  { date: "Dic 16", hours: 2.0 },
  { date: "Dic 17", hours: 1.0 },
  { date: "Dic 18", hours: 3.0 },
  { date: "Dic 19", hours: 0 },
  { date: "Dic 20", hours: 2.0 },
  { date: "Dic 21", hours: 1.0 },
  { date: "Dic 22", hours: 2.5 },
]
